services:
  mongo:
    image: mongo:latest
    container_name: park-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: park-backend
    restart: unless-stopped
    ports:
      - '5001:5000'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/park-recommendation?authSource=admin
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: park-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:5001/api
    depends_on:
      - backend

volumes:
  mongo-data:
